# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Creating kitchens"

Kitchen.create!(name: "Cuisine du 11ème", location: "2 rue Oberkampf 75011", price: 55, equipments: "four, plaques à induction, micro-ondes, grand plan de travail en bois", size: 10, availability: true, description: "cuisine spacieuse et fermé avec une fenêtre donnant sur une cour intérieure", picture: "app/assets/images/cuisine_du_11ème.jpeg")
Kitchen.create!(name: "Cuisine de chef", location: "5 rue De Levy 75017", price: 122, equipments: "four, gazinière, micro-ondes, plan de travail en marbre, Thermomix à disposition", size: 15, availability: true, description: "cuisine ouverte sur le salon, possibilité de cuisiner à plusieurs", picture: "app/assets/images/cuisine_de_chef.jpeg")
Kitchen.create!(name: "Cuisine Nordique", location: "12 rue Esquermoise 59000", price: 40, equipments: "four, plaques vitro céramique, micro-ondes, plan de travail en bois, couteaux janponais à disposition", size: 12, availability: true, description: "cuisine ouverte sur le salon, possibilité de cuisiner à plusieurs", picture: "app/assets/images/cusine-nordique")
Kitchen.create!(name: "Cuisine d'été", location: "12 rue Du vieux port Marseille", price: 30, equipments: "four, gazinière, micro-ondes, plan de travail en bois, barbecure, four à Pizza", size: 10, availability: true, description: "cuisine ouverte sur l'extérieur semi abritée", picture: "app/assets/images/cusine-extérieure")
Kitchen.create!(name: "Cuisine japonaise", location: "3 rue Du vieux port Marseille", price: 45, equipments: "four, gazinière, micro-ondes, plan de travail en bois", size: 13, availability: true, description: "cuisine tout en bois d'inspiration japaonaise pour cuisiner à plusieurs en toute sérénité", picture: "app/assets/images/cusine-inspiration-japonaise")Kitchen.create!(name: "Cuisine avec grand plan de travail", location: "Paris", price: 28, equipments: "", size: 20, availability: true,	description: "Cuisine avec espace de travail. Parfait pour toute les recettes demandant beaucoup d'espace. Cette cuisine vous permet de cuisiner à 2 ou 3 maximum",	picture: "https://images.unsplash.com/photo-1556911220-bff31c812dba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1135&q=80",	user_id: "")
Kitchen.create!(name: "Cuisine italienne pour pizza", location: "Paris", price: 36, equipments: "", size: 18, availability: true, description: "Cuisine spécialement conçpour la cuisine italienne. Vous pourrez faire des pizzas et calzone grace au beau four à feu de bois", picture: "https://images.unsplash.com/photo-1607375651527-ad191b70631d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",user_id: "")
Kitchen.create!(name: "Location avec cours", location: "Paris", price: 55, equipments: "", size: 28, availability: true, description: "Dans ce cours, je vais vous apprendre à faire des crêpes soufflées japonaises à partir de zéro. Les crêpes soufflées japonaises sont un régal léger, moelleux et alléchant qui sont servis dans les cafés partout au Japon. Ces crêpes sont un ajout amusant à votre répertoire de petit-déjeuner, brunch ou dessert. Étant donné que faire ces crêpes peut être délicat, nous ferons les crêpes une à la fois pour les pratiquer et je vous apprendrai tous les conseils dont vous avez besoin pour faire les crêpes parfaites. Au total, nous ferons 2 crêpes moelleuses.", picture: "https://images.unsplash.com/photo-1542967149-527e8af3ed35?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1189&q=80", user_id: "")

puts "Kitchens created"
